server.port=8082

spring.datasource.url=jdbc:postgresql://epic-order-postgres:5432/epic-order-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

user.service.url=${USER_SERVICE_URL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
